services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_NAME: ${NEXT_PUBLIC_SITE_NAME}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_SITE_DESCRIPTION: ${NEXT_PUBLIC_SITE_DESCRIPTION}
        NEXT_PUBLIC_OWNER_NAME: ${NEXT_PUBLIC_OWNER_NAME}
        NEXT_PUBLIC_JOB_TITLE: ${NEXT_PUBLIC_JOB_TITLE}
        NEXT_PUBLIC_LOGO_TEXT: ${NEXT_PUBLIC_LOGO_TEXT}
        NEXT_PUBLIC_ENABLE_TURNSTILE: ${NEXT_PUBLIC_ENABLE_TURNSTILE}
        NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
    container_name: portfolio_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    ports:
      - "3000:3000"
